<?php


namespace SOPHP\Core\Proxy;



use BadMethodCallException;
use SOPHP\Core\Proxy\Exception\MissingRpcClient;
use SOPHP\Zend\Json\Server\Client\ClientAwareInterface;
use Zend\Json\Server\Client;
use Zend\Log\Logger;
use Zend\Log\LoggerAwareInterface;
use Zend\Log\LoggerInterface;
use Zend\Log\Writer\Null;

abstract class Proxy implements ClientAwareInterface, LoggerAwareInterface {
    /** @var  Client */
    protected $_client;
    /** @var  LoggerInterface */
    protected $_log;

    /**
     * Return the string to the URI. Must be generated by the builder.
     * @return string
     */
    abstract public function _getUri();

    /**
     * @param Client $client
     * @return self
     */
    public function _setRpcClient(Client $client)
    {
        $this->_client = $client;
        return $this;
    }

    /**
     * Uses lazy instantiation if not available
     * @return Client
     */
    public function _getRpcClient()
    {
        if(!$this->_client) {
            $this->_client = new Client($this->_getUri());
        }
        return $this->_client;
    }

    /**
     * Proxy Magic!
     * usage: return $this->internalCallHandler(__FUNCTION__,func_get_args())
     * @param $method
     * @param $arguments
     * @throws MissingRpcClient
     * @throws \BadMethodCallException
     * @return string
     */
    protected function internalCallHandler($method, $arguments) {
        if(!method_exists($this, $method)) {
            throw new BadMethodCallException();
        }

        if(!$this->_getRpcClient()) {
            throw new MissingRpcClient();
        }

        $this->getLogger()->debug($method . ' called with ' . join(', ', $arguments));
        $this->getLogger()->debug(', will forward to ' . $this->_getUri());
        $result = $this->_getRpcClient()->call($method, $arguments);
        $this->getLogger()->debug(', and return ' . $result . PHP_EOL);
        return $result;
    }

    public function setLogger(LoggerInterface $logger)
    {
        $this->_log = $logger;
    }

    public function getLogger()
    {
        if(!$this->_log) {
            $this->_log = new Logger();
            $this->_log->addWriter(new Null());
        }
        return $this->_log;
    }
}